# Max number of attempts used for task run-time, each attempt is separated by 30s
attempt_limit: 80

# Max number of attempts before which code gives up waiting on resources
# (cpu/memory) to become available in the ecs cluster.
resources_attempt_limit: 20
initial_cluster_size: 2

# aws profile
profile_name: 'sit'

# Docker container configs
container_memory: 4096
container_memory_reservation: 1536
container_cpu: 512
container_image: 'dandb/salt_review:2015-8-3-external-redis'

# Logfile configs
save_logs: True
highstate_log_dir: highstate_logs
redis_host: 'redis-jenkins.devops.local'
