## CloudFormation stack name. Cannot contain underscores
stack_name: 'sit-tool'

## Cluster configs
cluster_name: 'sitCluster'

## CloudFormation template description
template_description: 'SIT (Salt Integration Testing) CloudFormation Template'

## launch configuration configs
launch_configuration_name: 'sitLaunchConfiguration'
instance_type: c5.2xlarge
security_groups: ['sg-44dac528']

key_name: KA_MBP

# AMI ID of amazon-ecs-optimized
ami_id: ami-00898660
ami_url: 'https://aws.amazon.com/marketplace/search/results/ref=dtl_navgno_search_box?page=1&searchTerms=Amazon+ECS-Optimized+Amazon+Linux+AMI'

# If you are using an amazon-ecs-optimized ami older than 2015.09c use '/dev/xvda' below
# http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html
ebs_device_name: '/dev/xvdcz'
ebs_volume_size: 200

subnet: subnet-6b0e4602

## Autoscaling Group configs
autoscaling_group_name: 'sitAutoScalingGroup'
max_size: 20
min_size: 0

autoscale_down_alarms:
  cpualarm:
    scaling_metric: 'CPUReservation'
    scale_down_threshold: '0'
    statistic: Average
    period: 900

autoscale_up_alarms:
  cpualarm:
    scaling_metric: 'CPUReservation'
    scale_up_threshold: '70'
    statistic: Average
    period: 60
  memoryalarm:
    scaling_metric: 'MemoryReservation'
    scale_up_threshold: '80'
    statistic: Average
    period: 60

ecs_task_cleanup_wait_duration: '3h'

## General configs
tag_key: 'Name'
tag_value: 'sit_tool'
